version: "3.9"
services:
  db:
    image: mysql:5.7.38
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
  web:
    build:
      context: .
    
    volumes:
      - .:/blog:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
